spring:
  datasource:
    url: jdbc:h2:mem:immudb
    username: sa
    password: 123
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name: bank-api
server:
  port: ${PORT:8081}

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka